services:
  Heimseiten\ContaoArticleImageBundle\Listener\HooksListener:
    tags:
      - { name: contao.hook, hook: compileArticle, method: onCompileArticle, priority: 0 }
      - { name: contao.hook, hook: parseTemplate, method: onParseTemplate, priority: 0 }
